title: Calvin Wong
description: Cybersecurity analyst candidate | Financial services operations professional | Toronto, Canada
url: "https://calvinwong.ca"
markdown: kramdown
plugins:
  - jekyll-sitemap
